"""create person table

Revision ID: ceecaa2ad064
Revises: 
Create Date: 2023-08-18 18:47:45.275449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceecaa2ad064'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Name of the Person'),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True, comment='Gender of the person'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date of Creation'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
